type Bookmark {
    id: ID!
    title: String!
    bookmark: String!
}

type Query {
    getBookmarks: [Bookmark!]
}

type Mutation {
    addBookmark(title: String!, bookmark: String!): Bookmark!
    deleteBookmark(id: String!): String!
    updateBookmark(id: String!, title: String!, bookmark: String!): Bookmark!
}